### ISSUE TITLE
Avoid possible segfaults

### ISSUE THREAD

**Issue by atroxaper** [jonathanstowe/Log-Syslog-Native#4]
The explicitly-manage returns externally using string instead of making the original string uncollectable by GC.
https://github.com/jonathanstowe/Log-Syslog-Native/blob/master/lib/Log/Syslog/Native.pm#L291

**Comment by jonathanstowe** [comment]
I'll try and make a release with this later today.

**Comment by jonathanstowe** [comment]
Made release v0.1.0 with this change
